//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimBilgiProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUTUPHANE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KUTUPHANE()
        {
            this.GOREVLI = new HashSet<GOREVLI>();
            this.VOLUME = new HashSet<VOLUME>();
        }
    
        public int KUTUPHANE_ID { get; set; }
        public string KUTUPHANE_Adi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOREVLI> GOREVLI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOLUME> VOLUME { get; set; }
    }
}
