//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimBilgiProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class kutuphaneDBEntities : DbContext
    {
        public kutuphaneDBEntities()
            : base("name=kutuphaneDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIL> DIL { get; set; }
        public virtual DbSet<GOREVLI> GOREVLI { get; set; }
        public virtual DbSet<KITAP> KITAP { get; set; }
        public virtual DbSet<KUTUPHANE> KUTUPHANE { get; set; }
        public virtual DbSet<ODUNC> ODUNC { get; set; }
        public virtual DbSet<TUR> TUR { get; set; }
        public virtual DbSet<UYE> UYE { get; set; }
        public virtual DbSet<VOLUME> VOLUME { get; set; }
        public virtual DbSet<YAYINCI> YAYINCI { get; set; }
        public virtual DbSet<YAZAR> YAZAR { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<string> SP_gorevliLogin(string gorevliTC, string gorevliSifre)
        {
            var gorevliTCParameter = gorevliTC != null ?
                new ObjectParameter("gorevliTC", gorevliTC) :
                new ObjectParameter("gorevliTC", typeof(string));
    
            var gorevliSifreParameter = gorevliSifre != null ?
                new ObjectParameter("gorevliSifre", gorevliSifre) :
                new ObjectParameter("gorevliSifre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_gorevliLogin", gorevliTCParameter, gorevliSifreParameter);
        }
    
        public virtual ObjectResult<string> SP_uyeLogin(string uyeTC, string uyeSifre)
        {
            var uyeTCParameter = uyeTC != null ?
                new ObjectParameter("uyeTC", uyeTC) :
                new ObjectParameter("uyeTC", typeof(string));
    
            var uyeSifreParameter = uyeSifre != null ?
                new ObjectParameter("uyeSifre", uyeSifre) :
                new ObjectParameter("uyeSifre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_uyeLogin", uyeTCParameter, uyeSifreParameter);
        }
    
        public virtual int SP_KitapEkle(string isbn, string adi, Nullable<int> turID, Nullable<int> yayinciID, Nullable<int> sayfa, Nullable<int> dilID, Nullable<int> kacTaneVar, Nullable<int> uygunSayi, Nullable<int> yazarID)
        {
            var isbnParameter = isbn != null ?
                new ObjectParameter("isbn", isbn) :
                new ObjectParameter("isbn", typeof(string));
    
            var adiParameter = adi != null ?
                new ObjectParameter("adi", adi) :
                new ObjectParameter("adi", typeof(string));
    
            var turIDParameter = turID.HasValue ?
                new ObjectParameter("turID", turID) :
                new ObjectParameter("turID", typeof(int));
    
            var yayinciIDParameter = yayinciID.HasValue ?
                new ObjectParameter("yayinciID", yayinciID) :
                new ObjectParameter("yayinciID", typeof(int));
    
            var sayfaParameter = sayfa.HasValue ?
                new ObjectParameter("sayfa", sayfa) :
                new ObjectParameter("sayfa", typeof(int));
    
            var dilIDParameter = dilID.HasValue ?
                new ObjectParameter("dilID", dilID) :
                new ObjectParameter("dilID", typeof(int));
    
            var kacTaneVarParameter = kacTaneVar.HasValue ?
                new ObjectParameter("kacTaneVar", kacTaneVar) :
                new ObjectParameter("kacTaneVar", typeof(int));
    
            var uygunSayiParameter = uygunSayi.HasValue ?
                new ObjectParameter("uygunSayi", uygunSayi) :
                new ObjectParameter("uygunSayi", typeof(int));
    
            var yazarIDParameter = yazarID.HasValue ?
                new ObjectParameter("yazarID", yazarID) :
                new ObjectParameter("yazarID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KitapEkle", isbnParameter, adiParameter, turIDParameter, yayinciIDParameter, sayfaParameter, dilIDParameter, kacTaneVarParameter, uygunSayiParameter, yazarIDParameter);
        }
    
        public virtual ObjectResult<string> SP_TurGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_TurGetir");
        }
    
        public virtual ObjectResult<SP_YazarGetir_Result> SP_YazarGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_YazarGetir_Result>("SP_YazarGetir");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SP_DilGetir_Result> SP_DilGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DilGetir_Result>("SP_DilGetir");
        }
    
        public virtual ObjectResult<SP_YayinciGetir_Result> SP_YayinciGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_YayinciGetir_Result>("SP_YayinciGetir");
        }
    
        public virtual ObjectResult<SP_TureGoreAra_Result> SP_TureGoreAra(string turAdi)
        {
            var turAdiParameter = turAdi != null ?
                new ObjectParameter("turAdi", turAdi) :
                new ObjectParameter("turAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TureGoreAra_Result>("SP_TureGoreAra", turAdiParameter);
        }
    
        public virtual ObjectResult<SP_KitapAdiylaAra_Result> SP_KitapAdiylaAra(string kitapAdi)
        {
            var kitapAdiParameter = kitapAdi != null ?
                new ObjectParameter("kitapAdi", kitapAdi) :
                new ObjectParameter("kitapAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KitapAdiylaAra_Result>("SP_KitapAdiylaAra", kitapAdiParameter);
        }
    
        public virtual ObjectResult<SP_ISBNileAra_Result> SP_ISBNileAra(string isbn)
        {
            var isbnParameter = isbn != null ?
                new ObjectParameter("isbn", isbn) :
                new ObjectParameter("isbn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ISBNileAra_Result>("SP_ISBNileAra", isbnParameter);
        }
    
        public virtual ObjectResult<SP_YazaraGoreAra_Result> SP_YazaraGoreAra(string yazarAdi)
        {
            var yazarAdiParameter = yazarAdi != null ?
                new ObjectParameter("yazarAdi", yazarAdi) :
                new ObjectParameter("yazarAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_YazaraGoreAra_Result>("SP_YazaraGoreAra", yazarAdiParameter);
        }
    }
}
