//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimBilgiProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODUNC
    {
        public System.DateTime ODUNC_AlmaTarihi { get; set; }
        public int ODUNC_VolumeID { get; set; }
        public string ODUNC_UyeTC { get; set; }
        public string ODUNC_VerenGorevliTC { get; set; }
        public string ODUNC_TeslimAlanGorevliTC { get; set; }
        public System.DateTime ODUNC_TeslimTarihi { get; set; }
    
        public virtual GOREVLI GOREVLI { get; set; }
        public virtual GOREVLI GOREVLI1 { get; set; }
        public virtual UYE UYE { get; set; }
        public virtual VOLUME VOLUME { get; set; }
    }
}
