//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimBilgiProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UYE()
        {
            this.ODUNC = new HashSet<ODUNC>();
        }
    
        public string UYE_TC { get; set; }
        public string UYE_Sifre { get; set; }
        public string UYE_Adi { get; set; }
        public string UYE_Soyadi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODUNC> ODUNC { get; set; }
    }
}
