//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimBilgiProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOLUME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOLUME()
        {
            this.ODUNC = new HashSet<ODUNC>();
        }
    
        public int VOLUME_ID { get; set; }
        public string VOLUME_KitapISBN { get; set; }
        public int VOLUME_KutuphaneID { get; set; }
        public bool VOLUME_UygunMu { get; set; }
    
        public virtual KITAP KITAP { get; set; }
        public virtual KUTUPHANE KUTUPHANE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODUNC> ODUNC { get; set; }
    }
}
